version: "3.1"
services:
  nies:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/sofa_score_data:latest
    command: bash
    volumes:
      - $PWD:/workdir
  nies_sofa:
    build:
      context: .
      dockerfile: Dockerfile_sofa
    image: nepolin/sofa_score_data_plot:latest
    command: bash
    volumes:
      - $PWD:/workdir